name: Testing
on:
  push:
    branches: "main"
  workflow_dispatch:
jobs:
  workflowtesting:
    env:
      testing: rajesh
    runs-on: centop-rfsh
    steps:
      - uses: actions/checkout@v4
      - name: This step used for Testing
        run: echo "This is" ${{ env.testing }}
        background: true
